name: Telegram Bot Runner

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '*/15 * * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
    - name: Kodni yuklab olish
      uses: actions/checkout@v3

    - name: Python o'rnatish
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Kutubxonalarni o'rnatish
      run: |
        pip install -r requirements.txt

    - name: Botni ishga tushirish
      run: |
        python main.py
